package com.mycompany.kelimeavigame.views;

import com.mycompany.kelimeavigame.models.ConnectionInfo;
import com.mycompany.kelimeavigame.models.Rules;
import com.mycompany.kelimeavigame.models.Server;
import javax.swing.SwingWorker;
import utils.Game;

public class ServerLogin extends javax.swing.JFrame {

    public ServerLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nicknameEditText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gameWidthEditText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        numOfBlocksEditText = new javax.swing.JTextField();
        gameHeightEditText = new javax.swing.JTextField();
        serverPortEditText = new javax.swing.JTextField();
        serverIPEditText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        winningPointsEditText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        numOfGamesEditText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        numOf2XEditText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        numOf3XEditText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setText("<  Back");
        backButton.setName(""); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Your Nickname");

        nicknameEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nicknameEditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknameEditTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Server IP");

        jLabel3.setText("Server Port");

        createButton.setText("CREATE");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Game Width");

        jLabel5.setText("Game Height");

        gameWidthEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gameWidthEditText.setFocusTraversalPolicyProvider(true);

        jLabel6.setText("Number Of Blocks");

        numOfBlocksEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numOfBlocksEditText.setFocusTraversalPolicyProvider(true);

        gameHeightEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gameHeightEditText.setFocusTraversalPolicyProvider(true);

        serverPortEditText.setFocusTraversalPolicyProvider(true);

        serverIPEditText.setFocusTraversalPolicyProvider(true);

        jLabel7.setText("Winning Points");

        winningPointsEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        winningPointsEditText.setFocusTraversalPolicyProvider(true);

        jLabel8.setText("Number Of Games");

        numOfGamesEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numOfGamesEditText.setFocusTraversalPolicyProvider(true);

        jLabel9.setText("Number Of 2X");

        numOf2XEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numOf2XEditText.setFocusTraversalPolicyProvider(true);

        jLabel10.setText("Number Of 3X");

        numOf3XEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numOf3XEditText.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(gameHeightEditText, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(numOfBlocksEditText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10))
                    .addComponent(numOfGamesEditText, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numOf3XEditText, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nicknameEditText, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serverIPEditText, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serverPortEditText, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addComponent(numOf2XEditText, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(winningPointsEditText, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(gameWidthEditText, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nicknameEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gameWidthEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameHeightEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numOfBlocksEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(winningPointsEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numOf2XEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numOf3XEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numOfGamesEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverIPEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(serverPortEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createButton)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        Intro introWindow = new Intro();
        introWindow.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void nicknameEditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknameEditTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicknameEditTextActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        createGame();
        dispose();
        ServerWaitingWindow waitingWindow = new ServerWaitingWindow();
        waitingWindow.addNewPlayerToList(Game.serverNickname);
        
        waitingWindow.setVisible(true);
    }//GEN-LAST:event_createButtonActionPerformed

    private void createGame() {
        Game.gameRules = getGameRuels();
        Game.serverConnectionInfo = getServerConnectionInfo();
        new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                Game.serverNickname = nicknameEditText.getText();
                Server server = new Server(Game.serverNickname);
                return null;
            }
        }.execute();

    }

    private Rules getGameRuels() {
        int gameWidth = Integer.parseInt(gameWidthEditText.getText());
        int gameHeight = Integer.parseInt(gameHeightEditText.getText());
        int numOfBlocks = Integer.parseInt(numOfBlocksEditText.getText());
        int winningPoints = Integer.parseInt(winningPointsEditText.getText());
        int numOfGames = Integer.parseInt(numOfGamesEditText.getText());
        int numOf2X = Integer.parseInt(numOf2XEditText.getText());
        int numOf3X = Integer.parseInt(numOf3XEditText.getText());
        return new Rules(gameWidth, gameHeight, numOfBlocks, winningPoints, numOfGames, numOf2X, numOf3X);
    }

    private ConnectionInfo getServerConnectionInfo() {
        String serverIP = serverIPEditText.getText();
        int ServerPort = Integer.parseInt(serverPortEditText.getText());
        return new ConnectionInfo(serverIP, ServerPort);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField gameHeightEditText;
    private javax.swing.JTextField gameWidthEditText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nicknameEditText;
    private javax.swing.JTextField numOf2XEditText;
    private javax.swing.JTextField numOf3XEditText;
    private javax.swing.JTextField numOfBlocksEditText;
    private javax.swing.JTextField numOfGamesEditText;
    private javax.swing.JTextField serverIPEditText;
    private javax.swing.JTextField serverPortEditText;
    private javax.swing.JTextField winningPointsEditText;
    // End of variables declaration//GEN-END:variables
}
